version: '3.8'

volumes:
  docker-nest-postgres:
networks:
  webnet:
    name: webnet
    driver: bridge

services:
    dev:
        container_name: nestjs-rest
        restart: always
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
           - ${PORT}:${PORT}
        networks:
            - webnet
        volumes:
            - type: bind
              source: ./src
              target: /home/nestjs-rest/src
            - ./logs:/home/nestjs-rest/logs
        env_file: 
            - .env
        depends_on:
            - postgres
    postgres:
        container_name: postgres
        image: postgres:1.0.0
        build: 
            dockerfile: ./database/Dockerfile
            context: .
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
        ports:
           - ${DB_PORT}:${DB_PORT}
        volumes:
            - docker-nest-postgres:/var/lib/postgresql/data 
        env_file: 
            - .env
